import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
                'h1': ['DM Sans'],
                'h2': ['DM Sans'],
                'h3': ['DM Sans'],
                'body': ['Inter'],
                'body-strong': ['Inter'],
                'caption': ['Inter'],
                'label-mono': ['JetBrains Mono'],
            },
            fontSize: {
                'h1': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'h2': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
                'h3': ['20px', { lineHeight: '28px', letterSpacing: '0', fontWeight: '700' }],
                'body': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
                'body-strong': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '600' }],
                'caption': ['12px', { lineHeight: '16px', letterSpacing: '0', fontWeight: '400' }],
                'label-mono': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
            },
            colors: {
                'primary': '#c0c1ff',
                'primary-container': '#8083ff',
                'primary-fixed': '#e1e0ff',
                'primary-fixed-dim': '#c0c1ff',
                'on-primary': '#1000a9',
                'on-primary-container': '#0d0096',
                'primary-fixed-variant': '#2f2ebe',
                'on-primary-fixed': '#07006c',
                'on-primary-fixed-variant': '#2f2ebe',
                'secondary': '#c2c6d7',
                'secondary-container': '#444956',
                'secondary-fixed': '#dee2f3',
                'secondary-fixed-dim': '#c2c6d7',
                'on-secondary': '#2b303d',
                'on-secondary-container': '#b4b8c8',
                'on-secondary-fixed': '#161b27',
                'on-secondary-fixed-variant': '#424754',
                'tertiary': '#ffb783',
                'tertiary-container': '#d97721',
                'tertiary-fixed': '#ffdcc5',
                'tertiary-fixed-dim': '#ffb783',
                'on-tertiary': '#4f2500',
                'on-tertiary-container': '#452000',
                'on-tertiary-fixed': '#301400',
                'on-tertiary-fixed-variant': '#703700',
                'surface': '#13131b',
                'surface-dim': '#13131b',
                'surface-bright': '#393841',
                'surface-container': '#1f1f27',
                'surface-container-low': '#1b1b23',
                'surface-container-lowest': '#0d0d15',
                'surface-container-high': '#292932',
                'surface-container-highest': '#34343d',
                'surface-tint': '#c0c1ff',
                'on-surface': '#e4e1ed',
                'on-surface-variant': '#c7c4d7',
                'inverse-surface': '#e4e1ed',
                'inverse-on-surface': '#303038',
                'background': '#13131b',
                'on-background': '#e4e1ed',
                'outline': '#908fa0',
                'outline-variant': '#464554',
                'error': '#ffb4ab',
                'error-container': '#93000a',
                'on-error': '#690005',
                'on-error-container': '#ffdad6',
                'inverse-primary': '#494bd6',
            },
            spacing: {
                'navbar_height': '56px',
                'sidebar_width': '240px',
                'container_padding': '24px',
                'gutter': '16px',
                'base_unit': '4px',
            },
            borderRadius: {
                'DEFAULT': '0.25rem',
                'lg': '0.5rem',
                'xl': '0.75rem',
                'full': '9999px',
            },
        },
    },

    plugins: [forms],
};
